language: ruby
rvm:
- 2.2.2
notifications:
  slack:
    secure: kSYTBC3ewvh+ipwBwhud9Vv0yLWWhfMpT18UyPJP2sJA3olnrJeOsVX5OKEEUf0l5OwbHJ0xbMTzXSwy7D8x47/iVIxLDVS919KU90UMf9C63PZE9GNjah7SrwBtD6uKmnUM9wL/xcpB15aQmgvqo+OUvw2BmkkSEAM7Y7sww2+8Wz5h9OASk+N7zBKYCrQy/UDswVNoh1cQ2+kQklOZbt3rSHENg0rHrSfp39Tebv0clml/kCFleoZJ5SG9hfktCME+Qfve5zAtW/Hgx/I/3LE5ayae8t9UkGT+LHFwWCvBjm8Xzn5BPK5CJY5OIJZyRRngQ7gj7EwPqu/SRf+stOM5osG521u8lJ8yHB8Tfwm2yK4kHw63GOZTbe565XyUBXxJg181sLLPGZI+zfRjFxRynuGxoISbGT3VbYbKL60bckz5DYAJdbhNySOSzr5GxyJQMiOsBb0mJTA3nbwAZwjYn0cVNWoJZrEqjizXIsU27Dv6pVoYblim7ZqToLIyp7lZCjwoxUeQkmVB/0QCVpG0YXTZmGvLWYRWXOVxne++oicuTuokF0ts0rQ53K89HngQqonze3P++6vh1Db0cTsrnDpC25AMTWKxWkpTm9Jjbdx5rj1S7cmU/ESAc/anav4dKvqPBy7UA2y33S3/e9QknGCMlwQlDwc5oJ7OMj8=
